name: quiz
description: A quiz app in flutter.
version: 1.1.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  html_unescape: any
  http: ^0.13.0
  sleek_circular_slider: ^2.0.0
  material_segmented_control: ^3.1.2
  flutter_bloc: ^7.0.0
  provider: ^5.0.0
  pinch_zoom_image_last: ^0.4.1
  dynamic_themes: ^1.1.0
  shared_preferences: ^2.0.6
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: true
  ios: false
  image_path: "assets/ios/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/ios/icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  